version: "3"

services:
  mysql:
    image: mysql:latest
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: 'mysql'
      PMA_PASSWORD: 'root'
    restart: unless-stopped

volumes:
  mysql: